# Generated by Django 4.0.1 on 2022-05-04 05:11

from django.db import migrations
import user.models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', user.models.UserManager()),
            ],
        ),
        migrations.RenameField(
            model_name='user',
            old_name='emil',
            new_name='email',
        ),
    ]
