# Generated by Django 4.0.1 on 2022-05-04 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_user_is_active_user_is_staff'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='age',
            field=models.IntegerField(blank=True, verbose_name='나이'),
        ),
    ]
